#!/usr/bin/env bash
# install and configure HAproxy

# Update package lists
sudo apt update
# enable dedicated ppa
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
# Install HAProxy
sudo apt-get install haproxy=2.8.\*

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    mode http
    default_backend web_servers

backend webservers
    balance roundrobin
    server web-01 442780-web-01 52.3.247.130:80 check
    server web-02 442780-web-02 54.234.30.56:80 check
EOF

# Manage HAProxy via init script
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Restart HAproxy
sudo service haproxy restart
